# Generated by Django 5.1.6 on 2025-02-22 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2000)),
                ('domain_name', models.CharField(max_length=255)),
                ('protocol', models.CharField(max_length=10)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('images', models.JSONField(default=list)),
                ('stylesheets_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
